services:
  app:
    build: .
    container_name: healthbeat_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/healthbeat
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: healthbeat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthbeat
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    container_name: healthbeat_redis
    ports:
      - "6379:6379"

networks:
  default:
    name: healthbeat_default
